apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  labels:
    app: qdrant
spec:
  clusterIP: None
  ports:
  - port: 6333
    name: http
  - port: 6334
    name: grpc
  selector:
    app: qdrant
